### PR TITLE
fix: reset scale & norm ranges in `scatter.data()`

### LINKED ISSUE #131: When updating the source data, xy point coordinates are clipped to original data range
- [x] Check for duplicate issues.
- [x] Use the latest versions of Jupyter Scatter.

- [x] Describe the bug: What did you do to trigger it? What was your expected behavior? And what did you experience instead?

* Create a scatter with an initial dataframe. 
* Replace the dataframe with `scatter.data(df_new)`
* Points try to migrate to their new locations but are "blocked" by the bounding box of the first dataframe
* Doesn't depend on current camera location

image

- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

```python
data1 = pd.DataFrame({
    "x": np.random.rand(1000),
    "y": np.random.rand(1000),
})
data2 = pd.DataFrame({
    "x": 2*np.random.rand(1000),
    "y": 2*np.random.rand(1000),
})
scatter = Scatter(data=data1, x="x", y="y", width=500, height=500)
scatter.show()
```

```python
scatter.data(data=data2)
```

### PR DESCRIPTION
**Pull request by flekschas**
Reset scale and norm ranges upon updating the associated dataframe.

## Description

> What was changed in this pull request?

Upon updating the referenced dataframe, all scale and norm ranges are reset such that they get re-computed with the new data.

E.g., first run

```py
import jscatter
import numpy as np
import pandas as pd

data1 = pd.DataFrame({
    "x": np.random.rand(1000),
    "y": np.random.rand(1000),
})
data2 = pd.DataFrame({
    "x": 2*np.random.rand(1000),
    "y": 2*np.random.rand(1000),
})
scatter = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
scatter.show()
```

Then

```py
scatter.data(data2)
```

https://github.com/flekschas/jupyter-scatter/assets/932103/f8878787-aa17-46d4-8607-ad625cc86024

> Why is it necessary?

Fixes #131 

## Checklist

- [x] Provided a concise title as a [semantic commit message](https://www.conventionalcommits.org) (e.g. "fix: correctly handle undefined properties")
- [x] `CHANGELOG.md` updated
- [x] Tests added or updated
- [ ] Documentation in `API.md`/`README.md` added or updated
- [ ] Example(s) added or updated
- [x] Screenshot, gif, or video attached for visual changes

### CODE REVIEW

**Comment by nvictus** [comment]
I think this is almost right. Notice that the axis labels displayed don't adjust to reflect the new data range. 

The `data1` is uniform in the unit square, while `data2` is uniform in ([0, 2], [0, 2]). Depending which dataframe you start with, it remains the same after changing to the other.

**Comment by nvictus** [comment]
The hacky way to make this example work as expected is:

```python
scatter = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
scatter.show()
```
```python
scatter._x_scale._clip = False
scatter._y_scale._clip = False
scatter.data(data2)
```

**Comment by flekschas** [comment]
Turns out the x/y (scale) domains where properly updated but the widget state wasn't set correctly! Now it should work properly (hopefully haha)


https://github.com/flekschas/jupyter-scatter/assets/932103/27d7db85-8143-44d8-8729-fc4ce904be62

**Comment by nvictus** [comment]
After playing with it, I think it would be more natural to keep the norms unchanged and make the points to migrate to their new places. I think what's happening above is that the point coordinates are getting renormalized to match different x and y scales on the same view space.

Here's what I get if I turn off norm clipping before the x and y coordinates are replaced and then reset the norm vmin and vmax **after** applying it to the points with `to_ndc` (I'm not sure if this will have unintended consequences):

```diff
diff --git a/jscatter/jscatter.py b/jscatter/jscatter.py
index e3bb9f8..baff2ff 100644
--- a/jscatter/jscatter.py
+++ b/jscatter/jscatter.py
@@ -504,8 +504,15 @@ class Scatter():

             self._points = np.zeros((self._n, 6))

+            xclip = self._x_scale.clip
+            yclip = self._y_scale.clip
+            self._x_scale.clip = False
+            self._y_scale.clip = False
             self.x(skip_widget_update=True, **self.x())
             self.y(skip_widget_update=True, **self.y())
+            self._x_scale.clip = xclip
+            self._y_scale.clip = yclip
+
             self.color(skip_widget_update=True, **self.color())
             self.opacity(skip_widget_update=True, **self.opacity())
             self.size(skip_widget_update=True, **self.size())
@@ -616,6 +623,9 @@ class Scatter():
                 self.get_histogram_range("x")
             )

+            # Normalize x coordinate to [-1,1]
+            self._points[:, 0] = to_ndc(self._points[:, 0], self._x_scale)
+
             # Reset scale to new domain
             if scale is UNDEF:
                 try:
@@ -624,9 +634,6 @@ class Scatter():
                 except ValueError:
                     pass

-            # Normalize x coordinate to [-1,1]
-            self._points[:, 0] = to_ndc(self._points[:, 0], self._x_scale)
-
             self._x_scale_domain = [self._x_scale.vmin, self._x_scale.vmax]

             if 'skip_widget_update' not in kwargs:
@@ -732,6 +739,9 @@ class Scatter():
                 self.get_histogram_range("y")
             )

+            # Normalize y coordinate to [-1,1]
+            self._points[:, 1] = to_ndc(self._points[:, 1], self._y_scale)
+
             # Reset scale to new domain
             if scale is UNDEF:
                 try:
@@ -740,9 +750,6 @@ class Scatter():
                 except ValueError:
                     pass

-            # Normalize y coordinate to [-1,1]
-            self._points[:, 1] = to_ndc(self._points[:, 1], self._y_scale)
-
             self._y_scale_domain = [self._y_scale.vmin, self._y_scale.vmax]
```


Screen Recording 2024-06-11 at 10 51 02 AM

**Comment by flekschas** [comment]
I see the value in keeping the view fixed in your example (where the points likely reference the same data records) but what about cases where the data range changes dramatically or you're loading a df where the number of points changes dramatically? Wouldn't it be nice to reset the view in these cases?

Another idea is we could make the behavior explicit. Something like

```py
scatter.data(new_data, keep_view=True)
# or
scatter.data(new_data, reset_view=True)
```

The problem with not normalizing the coordinates to normalized device coordinates is that the view reset button won't work as expected anymore: usually it resets the camera such that all points are visible by setting the view to [-1, 1] but if points are now located across [-10, 10] (as an example) then the default view will not show all points.

**Comment by nvictus** [comment]
Yes, that makes sense. I've noticed that in the latter case (number of points changes), no animation occurs: the old points are replaced with a different set of points. It makes sense to me to reset the view (norms) in that scenario.

In the former case (same number of points but data range changes), there is animation: jscatter is treating the new data as new locations of the same points. However, that might not always be the user's intention.

In the case of moving points, I can imagine preserving the original view (t=0) and optionally moving the camera to the new data limits but not resetting the norms. I would argue that if the norms are reset, then it would be misleading to animate the point movement, so it should probably be disabled if that is the intention.

> Another idea is we could make the behavior explicit.

It seems that these two use cases have different intentions, so I think the question is how to make those intentions explicit.

**Comment by abast** [comment]
I would also express my interest to (at least have the option to) keep the view fixed. I think the visualization can easily become a bit misleading otherwise. For example, if I see an animation in which points are moving within the same square, I would get the impression they have the same scale. This may be useful in some scenarios, but I would argue that by default, this aspect of the data should not be hidden. Additionally, I think it would be good to give the guarantee that if a point moves to the right side, it means that its x-value increased. But if the view is reset, depending on what the new bounds are, even the opposite might happen (x value of a point increases, but the animation shows a movement to the left side), which I would find very confusing. 

> It seems that these two use cases (brand new points vs moving points) have different intentions, so I think the question is how to make those intentions explicit.
Maybe by implementing functions similar to ax.set_xlim, ax.set_ylim and ax.set_aspect in matplotlib? 

Related: https://github.com/flekschas/jupyter-scatter/issues/104

**Comment by flekschas** [comment]
Alright, I've refactored `scatter.data()` to make the behavior more explicit by adding three new arguments:
- `reset_scales`: If `True`, the scales will be reset. Most users shouldn't care about this argument but it can be useful if you want to make the new data extent the de facto default view. Or in other terms, the normalized device coordinate space is adjusted to the new data extent.
- `reset_view`: If `True`, the view will reset such that the entire dataset is shown.
- `animate`: If `True` and if `reset_scales` is `False`, the points will transition smoothly if and only if the number of points is unchanged. Additionally, if `reset_view` is `True` the view will also transition smoothly.

The new default behavior is that the view is not reset and the scales remain unchanged. Points are also not animated by default irrespective of whether the number of points remains unchanged or now.

Here's a video demonstrating the different behavior

https://github.com/flekschas/jupyter-scatter/assets/932103/fd1b34a2-ab2e-4bb7-aba6-40e934a81453

@nvictus What do you think?

Oh the other thing to note is that I've turned off default clipping. I found that to be an odd behavior. One can of course still enable clipping by passing in a custom norm.

> Maybe by implementing functions similar to ax.set_xlim, ax.set_ylim and ax.set_aspect in matplotlib?

@abast I've responded to your question in #104 already.

**Comment by nvictus** [comment]
This looks great! Thank you, @flekschas.

> Oh the other thing to note is that I've turned off default clipping. I found that to be an odd behavior.

Agreed!

**Pull request merged**
